/**
 * Generated data model types for Convex
 * This file is automatically generated by Convex
 */
export type DataModel = {
  tasks: {
    _id: string;
    title: string;
    description?: string;
    completed: boolean;
    priority: "low" | "medium" | "high";
    dueDate?: string;
    createdAt: number;
    updatedAt: number;
    userId: string;
  };
  users: {
    _id: string;
    name: string;
    email: string;
    image?: string;
  };
};

export type Id<T extends keyof DataModel> = string;
